// JavaScript Document
/**
 * Created by shamsad.ahmad on 14/01/2016.
 */
var services=angular.module('listService',[]);

//We can create n number of factory(service) to be used for various places.
services.factory("CountryStateService", ['$filter', '$http', function($filter,$http){
    var service = {};


    var countrylist = [
        { "id": 1, "country": "Canada" }
    ];

    var statelist = [
       	{"Id":1, "state":"New Brunswick", "country": "Canada"},
        {"Id":2, "state":"Manitoba", "country": "Canada"},
        {"Id":3, "state":"Alberta", "country": "Canada"},
        {"Id":4, "state":"British Columbia", "country": "Canada"},
        {"Id":5, "state":"Newfoundlandand Labrador", "country": "Canada"},
        {"Id":6, "state":"Northwest Territories", "country": "Canada"},
        {"Id":7, "state":"Nova Scotia", "country": "Canada"},
        {"Id":8, "state":"Ontario", "country": "Canada"},
        {"Id":9, "state":"Prince Edward Island", "country": "Canada"},
        {"Id":10, "state":"Quebec", "country": "Canada"},
        {"Id":11, "state":"Saskatchewan", "country": "Canada"},
        {"Id":12, "state":"Yukon Territory", "country": "Canada"}
    ];

    var citylist = [
       
        {"Id":1, "city":"Airdrie", "state": "Alberta"},
        {"Id":2, "city":"Airdrie", "state": "Alberta"},
        {"Id":3, "city":"Beaumont", "state": "Alberta"},
        {"Id":4, "city":"Bonnyville", "state": "Alberta"},
        {"Id":5, "city":"Brazeau", "state": "Alberta"},
        {"Id":6, "city":"Breton", "state": "Alberta"},
        {"Id":7, "city":"Calgary", "state": "Alberta"},
        {"Id":8, "city":"Camrose", "state": "Alberta"},
        {"Id":9, "city":"Canmore", "state": "Alberta"},
        {"Id":10, "city":"Didzbury", "state": "Alberta"},
        {"Id":11, "city":"Drayton Valley", "state": "Alberta"},
        {"Id":12, "city":"Edmonton", "state": "Alberta"},
        {"Id":13, "city":"Ft. Saskatchewan", "state": "Alberta"},
        {"Id":14, "city":"Grande Prairie", "state": "Alberta"},
        {"Id":15, "city":"Hanna", "state": "Alberta"},
        {"Id":16, "city":"Hinton", "state": "Alberta"},
        {"Id":17, "city":"Irricana", "state": "Alberta"},
        {"Id":18, "city":"Lacombe", "state": "Alberta"},
        {"Id":19, "city":"Leduc", "state": "Alberta"},
        {"Id":20, "city":"Lethbridge", "state": "Alberta"},
        {"Id":21, "city":"McLennan", "state": "Alberta"},
        {"Id":22, "city":"Medicine Hat", "state": "Alberta"},
        {"Id":23, "city":"Olds", "state": "Alberta"},
        {"Id":24, "city":"Onoway", "state": "Alberta"},
        {"Id":25, "city":"Provost", "state": "Alberta"},
        {"Id":26, "city":"Red Deer", "state": "Alberta"},
        {"Id":27, "city":"St. Albert", "state": "Alberta"},
        {"Id":28, "city":"Spruce Grove", "state": "Alberta"},
        {"Id":29, "city":"Strathcona County", "state": "Alberta"},
        {"Id":30, "city":"Strathmore", "state": "Alberta"},
        {"Id":31, "city":"Sylvan lake", "state": "Alberta"},
        {"Id":32, "city":"Swan Hills", "state": "Alberta"},
        {"Id":33, "city":"Taber", "state": "Alberta"},
        {"Id":34, "city":"Turner Valley", "state": "Alberta"},
        {"Id":35, "city":"Vermillion", "state": "Alberta"},
        {"Id":36, "city":"Wood Buffalo", "state": "Alberta"},
        {"Id":37, "city":"Burnaby", "state": "British Columbia"},        
        {"Id":38, "city":"Lumby", "state": "British Columbia"},
        {"Id":39, "city":"City of Port Moody", "state": "British Columbia"},
        {"Id":40, "city":"Cache Creek", "state": "British Columbia"},
        {"Id":41, "city":"Maple Ridge", "state": "British Columbia"},
        {"Id":42, "city":"Prince George", "state": "British Columbia"},
        {"Id":43, "city":"Castlegar", "state": "British Columbia"},
        {"Id":44, "city":"Merritt", "state": "British Columbia"},
        {"Id":45, "city":"Prince Rupert", "state": "British Columbia"},
        {"Id":46, "city":"Chemainus", "state": "British Columbia"},
        {"Id":47, "city":"Mission", "state": "British Columbia"},
        {"Id":48, "city":"City of Richmond", "state": "British Columbia"},
        {"Id":49, "city":"Chilliwack", "state": "British Columbia"},
        {"Id":50, "city":"Nanaimo", "state": "British Columbia"},
        {"Id":51, "city":"Saanich", "state": "British Columbia"},
        {"Id":52, "city":"Clearwater", "state": "British Columbia"},
        {"Id":53, "city":"Nelson", "state": "British Columbia"},
        {"Id":54, "city":"Sooke", "state": "British Columbia"},
        {"Id":55, "city":"City of Colwood", "state": "British Columbia"},
        {"Id":56, "city":"New Westminster", "state": "British Columbia"},
        {"Id":57, "city":"Sparwood", "state": "British Columbia"},
        {"Id":58, "city":"Coquitlam", "state": "British Columbia"},
        {"Id":59, "city":"North Cowichan", "state": "British Columbia"},
        {"Id":60, "city":"Surrey", "state": "British Columbia"},
        {"Id":61, "city":"Cranbrook", "state": "British Columbia"},
        {"Id":62, "city":"North Vancouver", "state": "British Columbia"},
        {"Id":63, "city":"Terrace", "state": "British Columbia"},
        {"Id":64, "city":"Dawson Creek", "state": "British Columbia"},
        {"Id":65, "city":"North Vancouver (District)", "state": "British Columbia"},
        {"Id":66, "city":"Tumbler", "state": "British Columbia"},
        {"Id":67, "city":"Delta", "state": "British Columbia"},
        {"Id":68, "city":"Osoyoos", "state": "British Columbia"},
        {"Id":69, "city":"Vancouver", "state": "British Columbia"},
        {"Id":70, "city":"Fernie", "state": "British Columbia"},
        {"Id":71, "city":"Parksville", "state": "British Columbia"},
        {"Id":72, "city":"Vancouver (Region)", "state": "British Columbia"},
        {"Id":73, "city":"Invermere", "state": "British Columbia"},
        {"Id":74, "city":"Peace River", "state": "British Columbia"},
        {"Id":75, "city":"Vernon", "state": "British Columbia"},
        {"Id":76, "city":"Kamloops", "state": "British Columbia"},
        {"Id":77, "city":"Penticton", "state": "British Columbia"},
        {"Id":78, "city":"Victoria", "state": "British Columbia"},
        {"Id":79, "city":"Kaslo", "state": "British Columbia"},
        {"Id":80, "city":"Port Alberni", "state": "British Columbia"},
        {"Id":81, "city":"Whistler", "state": "British Columbia"},
        {"Id":82, "city":"Langley", "state": "British Columbia"},
        {"Id":83, "city":"Port Hardy", "state": "British Columbia"},
        {"Id":84, "city":"Birtle", "state": "Manitoba"},
        {"Id":85, "city":"Flin Flon", "state": "Manitoba"},
        {"Id":86, "city":"Swan River", "state": "Manitoba"},
        {"Id":87, "city":"Brandon", "state": "Manitoba"},
        {"Id":88, "city":"Snow Lake", "state": "Manitoba"},
        {"Id":89, "city":"The Pas", "state": "Manitoba"},
        {"Id":90, "city":"Cranberry Portage", "state": "Manitoba"},
        {"Id":100, "city":"Stein Bach", "state": "Manitoba"},
        {"Id":101, "city":"Thompson", "state": "Manitoba"},
        {"Id":102, "city":"Dauphin", "state": "Manitoba"},
        {"Id":103, "city":"Stonewall", "state": "Manitoba"},
        {"Id":104, "city":"Winnipeg", "state": "Manitoba"},
        {"Id":105, "city":"Cap-Pele", "state": "New Brunswick"},
        {"Id":106, "city":"Miramichi", "state": "New Brunswick"},
        {"Id":107, "city":"Saint John", "state": "New Brunswick"},
        {"Id":108, "city":"Fredericton", "state": "New Brunswick"},
        {"Id":109, "city":"Moncton", "state": "New Brunswick"},
        {"Id":110, "city":"Saint Stephen", "state": "New Brunswick"},
        {"Id":111, "city":"Grand Bay-Westfield", "state": "New Brunswick"},
        {"Id":112, "city":"Oromocto", "state": "New Brunswick"},
        {"Id":113, "city":"Shippagan", "state": "New Brunswick"},
        {"Id":114, "city":"Grand Falls", "state": "New Brunswick"},
        {"Id":115, "city":"Port Elgin", "state": "New Brunswick"},
        {"Id":116, "city":"Sussex", "state": "New Brunswick"},
        {"Id":117, "city":"Memramcook", "state": "New Brunswick"},
        {"Id":118, "city":"Sackville", "state": "New Brunswick"},
        {"Id":119, "city":"Tracadie-Sheila", "state": "New Brunswick"},
        {"Id":120, "city":"Argentia", "state": "Newfoundlandand Labrador"},
        {"Id":121, "city":"Corner Brook", "state": "Newfoundlandand Labrador"},
        {"Id":122, "city":"Paradise", "state": "Newfoundlandand Labrador"},
        {"Id":123, "city":"Bishop's Falls", "state": "Newfoundlandand Labrador"},
        {"Id":124, "city":"Labrador City", "state": "Newfoundlandand Labrador"},
        {"Id":125, "city":"Portaux Basques", "state": "Newfoundlandand Labrador"},
        {"Id":126, "city":"Botwood", "state": "Newfoundlandand Labrador"},
        {"Id":127, "city":"Mount Pearl", "state": "Newfoundlandand Labrador"},
        {"Id":128, "city":"St. John's", "state": "Newfoundlandand Labrador"},
        {"Id":129, "city":"Brigus", "state": "Newfoundlandand Labrador"},
        {"Id":130, "city":"Town of Hay River", "state": "Northwest Territories"},
        {"Id":131, "city":"Town of Inuvik", "state": "Northwest Territories"},
        {"Id":132, "city":"Yellowknife", "state": "Northwest Territories"},
        {"Id":133, "city":"Amherst", "state": "Nova Scotia"},
        {"Id":134, "city":"Hants County", "state": "Nova Scotia"},
        {"Id":135, "city":"Pictou", "state": "Nova Scotia"},
        {"Id":136, "city":"Annapolis", "state": "Nova Scotia"},
        {"Id":137, "city":"Inverness County", "state": "Nova Scotia"},
        {"Id":138, "city":"Pictou County", "state": "Nova Scotia"},
        {"Id":139, "city":"Argyle", "state": "Nova Scotia"},
        {"Id":140, "city":"Kentville", "state": "Nova Scotia"},
        {"Id":141, "city":"Queens", "state": "Nova Scotia"},
        {"Id":142, "city":"Baddeck", "state": "Nova Scotia"},
        {"Id":143, "city":"County of Kings", "state": "Nova Scotia"},
        {"Id":144, "city":"Richmond", "state": "Nova Scotia"},
        {"Id":145, "city":"Bridgewater", "state": "Nova Scotia"},
        {"Id":146, "city":"Lunenburg", "state": "Nova Scotia"},
        {"Id":147, "city":"Shelburne", "state": "Nova Scotia"},
        {"Id":148, "city":"Cape Breton", "state": "Nova Scotia"},
        {"Id":149, "city":"Lunenburg County", "state": "Nova Scotia"},
        {"Id":150, "city":"Stellarton", "state": "Nova Scotia"},
        {"Id":151, "city":"Chester", "state": "Nova Scotia"},
        {"Id":152, "city":"Mahone Bay", "state": "Nova Scotia"},
        {"Id":153, "city":"Truro", "state": "Nova Scotia"},
        {"Id":154, "city":"Cumberland County", "state": "Nova Scotia"},
        {"Id":155, "city":"New Glasgow", "state": "Nova Scotia"},
        {"Id":156, "city":"Windsor", "state": "Nova Scotia"},
        {"Id":157, "city":"East Hants", "state": "Nova Scotia"},
        {"Id":158, "city":"New Minas", "state": "Nova Scotia"},
        {"Id":159, "city":"Yarmouth", "state": "Nova Scotia"},
        {"Id":160, "city":"Halifax", "state": "Nova Scotia"},
        {"Id":161, "city":"Parrsboro", "state": "Nova Scotia"},
        {"Id":162, "city":"Ajax", "state": "Ontario"},
        {"Id":163, "city":"Halton", "state": "Ontario"},
        {"Id":164, "city":"Peterborough", "state": "Ontario"},
        {"Id":165, "city":"Atikokan", "state": "Ontario"},
        {"Id":166, "city":"Halton Hills", "state": "Ontario"},
        {"Id":167, "city":"Pickering", "state": "Ontario"},
        {"Id":168, "city":"Barrie", "state": "Ontario"},
        {"Id":169, "city":"Hamilton", "state": "Ontario"},
        {"Id":170, "city":"Port Bruce", "state": "Ontario"},
        {"Id":171, "city":"Belleville", "state": "Ontario"},
        {"Id":172, "city":"Hamilton-Wentworth", "state": "Ontario"},
        {"Id":173, "city":"Port Burwell", "state": "Ontario"},
        {"Id":174, "city":"Blandford-Blenheim", "state": "Ontario"},
        {"Id":175, "city":"Hearst", "state": "Ontario"},
        {"Id":176, "city":"Port Colborne", "state": "Ontario"},
        {"Id":177, "city":"Blind River", "state": "Ontario"},
        {"Id":178, "city":"Huntsville", "state": "Ontario"},
        {"Id":179, "city":"Port Hope", "state": "Ontario"},
        {"Id":180, "city":"Brampton", "state": "Ontario"},
        {"Id":181, "city":"Ingersoll", "state": "Ontario"},
        {"Id":182, "city":"Prince edward", "state": "Ontario"},
        {"Id":183, "city":"Brant", "state": "Ontario"},
		{"Id":184, "city":"James", "state": "Ontario"},
		{"Id":185, "city":"Quinte west", "state": "Ontario"},
		{"Id":186, "city":"Brantford", "state": "Ontario"},
		{"Id":187, "city":"Kanata", "state": "Ontario"},
		{"Id":188, "city":"Renfrew", "state": "Ontario"},
		{"Id":189, "city":"Brock", "state": "Ontario"},
		{"Id":190, "city":"Kincardine", "state": "Ontario"},
		{"Id":191, "city":"Richmond Hill", "state": "Ontario"},
		{"Id":192, "city":"Brockville", "state": "Ontario"},
		{"Id":193, "city":"King", "state": "Ontario"},
		{"Id":194, "city":"Sarnia", "state": "Ontario"},
		{"Id":195, "city":"Burlington", "state": "Ontario"},
		{"Id":196, "city":"Kingston", "state": "Ontario"},
		{"Id":197, "city":"Sault Ste. Marie", "state": "Ontario"},
		{"Id":198, "city":"Caledon", "state": "Ontario"},
		{"Id":199, "city":"Kirkland Lake", "state": "Ontario"},
		{"Id":200, "city":"Scarborough", "state": "Ontario"},
		{"Id":201, "city":"Cambridge", "state": "Ontario"},
		{"Id":202, "city":"Kitchener", "state": "Ontario"},
		{"Id":203, "city":"Scugog Souix Lookout", "state": "Ontario"},
		{"Id":204, "city":"Chatham-Kent", "state": "Ontario"},
		{"Id":205, "city":"Larder Lake", "state": "Ontario"},
		{"Id":206, "city":"Sioux Lookout", "state": "Ontario"},
		{"Id":207, "city":"Chester Ville", "state": "Ontario"},
		{"Id":208, "city":"Leamington", "state": "Ontario"},
		{"Id":209, "city":"Smith Falls", "state": "Ontario"},
		{"Id":210, "city":"Clarington", "state": "Ontario"},
		{"Id":211, "city":"Lennox-addington", "state": "Ontario"},
		{"Id":212, "city":"South-West Oxford", "state": "Ontario"},
		{"Id":213, "city":"Lincoln", "state": "Ontario"},
		{"Id":214, "city":"St. Catharines", "state": "Ontario"},
		{"Id":215, "city":"Cochrane", "state": "Ontario"},
		{"Id":216, "city":"Lindsay", "state": "Ontario"},
		{"Id":217, "city":"St. thomas", "state": "Ontario"},
		{"Id":218, "city":"Collingwood", "state": "Ontario"},
		{"Id":219, "city":"London", "state": "Ontario"},
		{"Id":220, "city":"Stoney Creek", "state": "Ontario"},
		{"Id":221, "city":"Cornwall", "state": "Ontario"},
		{"Id":222, "city":"Loyalist Township", "state": "Ontario"},
		{"Id":223, "city":"Stratford", "state": "Ontario"},
		{"Id":224, "city":"Cumberland", "state": "Ontario"},
		{"Id":225, "city":"Markham", "state": "Ontario"},
		{"Id":226, "city":"Sudbury", "state": "Ontario"},
		{"Id":227, "city":"Deep River", "state": "Ontario"},
		{"Id":228, "city":"Metro Toronto", "state": "Ontario"},
		{"Id":229, "city":"Temagami", "state": "Ontario"},
		{"Id":230, "city":"Dundas", "state": "Ontario"},
		{"Id":231, "city":"Merrickville", "state": "Ontario"},
		{"Id":232, "city":"Thorold", "state": "Ontario"},
		{"Id":233, "city":"Durham", "state": "Ontario"},
		{"Id":234, "city":"Milton", "state": "Ontario"},
		{"Id":235, "city":"Thunder Bay", "state": "Ontario"},
		{"Id":236, "city":"Dymond", "state": "Ontario"},
		{"Id":237, "city":"Nepean", "state": "Ontario"},
		{"Id":238, "city":"Tillsonburg", "state": "Ontario"},
		{"Id":239, "city":"Ear falls", "state": "Ontario"},
		{"Id":240, "city":"New Market", "state": "Ontario"},
		{"Id":241, "city":"Timmins", "state": "Ontario"},
		{"Id":242, "city":"East Gwillimbury", "state": "Ontario"},
		{"Id":243, "city":"Niagara", "state": "Ontario"},
		{"Id":244, "city":"Toronto", "state": "Ontario"},
		{"Id":245, "city":"East Zorra-Tavistock", "state": "Ontario"},
		{"Id":246, "city":"Niagara Falls", "state": "Ontario"},
		{"Id":247, "city":"Uxbridge", "state": "Ontario"},
		{"Id":248, "city":"Niagara-on-the-lake", "state": "Ontario"},
		{"Id":249, "city":"Vaughan", "state": "Ontario"},
		{"Id":250, "city":"Elliot Lake", "state": "Ontario"},
		{"Id":251, "city":"North Bay", "state": "Ontario"},
		{"Id":252, "city":"Wainfleet", "state": "Ontario"},
		{"Id":253, "city":"Flamborough", "state": "Ontario"},
		{"Id":254, "city":"North Dorchester", "state": "Ontario"},
		{"Id":255, "city":"Wasaga Beach", "state": "Ontario"},
		{"Id":256, "city":"Fort Erie", "state": "Ontario"},
		{"Id":257, "city":"North Dumfries", "state": "Ontario"},
		{"Id":258, "city":"Waterloo", "state": "Ontario"},
		{"Id":259, "city":"Fort Frances", "state": "Ontario"},
		{"Id":260, "city":"North York", "state": "Ontario"},
		{"Id":261, "city":"Waterloo (Region)", "state": "Ontario"},
		{"Id":262, "city":"Gananoque", "state": "Ontario"},
		{"Id":263, "city":"Norwich", "state": "Ontario"},
		{"Id":264, "city":"Welland", "state": "Ontario"},
		{"Id":265, "city":"Georgina", "state": "Ontario"},
		{"Id":266, "city":"Oakville", "state": "Ontario"},
		{"Id":267, "city":"Wellesley", "state": "Ontario"},
		{"Id":268, "city":"Glanbrook", "state": "Ontario"},
		{"Id":269, "city":"Orangeville", "state": "Ontario"},
		{"Id":270, "city":"West Carleton", "state": "Ontario"},
		{"Id":271, "city":"Gloucester", "state": "Ontario"},
		{"Id":280, "city":"Orillia", "state": "Ontario"},
		{"Id":281, "city":"West Lincoln", "state": "Ontario"},
		{"Id":282, "city":"Goulbourn", "state": "Ontario"},
		{"Id":283, "city":"Osgoode", "state": "Ontario"},
		{"Id":284, "city":"Whitby", "state": "Ontario"},
		{"Id":285, "city":"Gravenhurst", "state": "Ontario"},
		{"Id":286, "city":"Oshawa", "state": "Ontario"},
		{"Id":287, "city":"Wilmot", "state": "Ontario"},
		{"Id":288, "city":"Grimsby", "state": "Ontario"},
		{"Id":289, "city":"Ottawa", "state": "Ontario"},
		{"Id":290, "city":"Windsor", "state": "Ontario"},
		{"Id":291, "city":"Guelph", "state": "Ontario"},
		{"Id":292, "city":"Ottwa-Carleton", "state": "Ontario"},
		{"Id":293, "city":"Woolwich", "state": "Ontario"},
		{"Id":294, "city":"Haldimand-Norfork", "state": "Ontario"},
		{"Id":295, "city":"Owen Sound Oxford", "state": "Ontario"},
		{"Id":296, "city":"York", "state": "Ontario"},
		{"Id":297, "city":"Alberton", "state": "Prince Edward Island"},
		{"Id":298, "city":"Montague", "state": "Prince Edward Island"},
		{"Id":299, "city":"Stratford", "state": "Prince Edward Island"},
		{"Id":300, "city":"Charlottetown", "state": "Prince Edward Island"},
		{"Id":301, "city":"Souris", "state": "Prince Edward Island"},
		{"Id":302, "city":"Summerside", "state": "Prince Edward Island"},
		{"Id":303, "city":"Cornwall", "state": "Prince Edward Island"},
		{"Id":304, "city":"Alma", "state": "Quebec"},
		{"Id":305, "city":"Fleurimont", "state": "Quebec"},
		{"Id":306, "city":"Longueuil", "state": "Quebec"},
		{"Id":307, "city":"Almos", "state": "Quebec"},
		{"Id":308, "city":"Gaspe-Office of Tourism", "state": "Quebec"},
		{"Id":309, "city":"Marieville", "state": "Quebec"},
		{"Id":310, "city":"Anjou", "state": "Quebec"},
		{"Id":311, "city":"Gatineau", "state": "Quebec"},
		{"Id":312, "city":"Mount Royal", "state": "Quebec"},
		{"Id":313, "city":"Aylmer", "state": "Quebec"},
		{"Id":314, "city":"Hull", "state": "Quebec"},
		{"Id":315, "city":"Montreal City", "state": "Quebec"},
		{"Id":316, "city":"Beauport", "state": "Quebec"},
		{"Id":317, "city":"Joliette", "state": "Quebec"},
		{"Id":318, "city":"Montreal Region", "state": "Quebec"},
		{"Id":319, "city":"Bromptonville", "state": "Quebec"},
		{"Id":320, "city":"Jonquiere", "state": "Quebec"},
		{"Id":321, "city":"Montreal-Est", "state": "Quebec"},
		{"Id":322, "city":"Brosssard", "state": "Quebec"},
		{"Id":323, "city":"Lachine", "state": "Quebec"},
		{"Id":324, "city":"Quebec", "state": "Quebec"},
		{"Id":325, "city":"Chateauguay", "state": "Quebec"},
		{"Id":326, "city":"Lasalle", "state": "Quebec"},
		{"Id":327, "city":"Saint-Leonard", "state": "Quebec"},
		{"Id":328, "city":"Chicoutimi", "state": "Quebec"},
		{"Id":329, "city":"Laurentides", "state": "Quebec"},
		{"Id":330, "city":"Sherbrooke", "state": "Quebec"},
		{"Id":331, "city":"Coaticook", "state": "Quebec"},
		{"Id":332, "city":"Laval", "state": "Quebec"},
		{"Id":333, "city":"Thetford Mines", "state": "Quebec"},
		{"Id":334, "city":"City of Dorval", "state": "Quebec"},
		{"Id":335, "city":"Lennoxville", "state": "Quebec"},
		{"Id":336, "city":"Victoriaville", "state": "Quebec"},
		{"Id":337, "city":"Drummondville", "state": "Quebec"},
		{"Id":338, "city":"Avonlea", "state": "Saskatchewan"},
		{"Id":339, "city":"Melfort", "state": "Saskatchewan"},
		{"Id":340, "city":"Swift Current", "state": "Saskatchewan"},
		{"Id":341, "city":"Colonsay", "state": "Saskatchewan"},
		{"Id":342, "city":"Nipawin", "state": "Saskatchewan"},
		{"Id":343, "city":"Tisdale", "state": "Saskatchewan"},
		{"Id":344, "city":"Craik", "state": "Saskatchewan"},
		{"Id":345, "city":"Prince Albert", "state": "Saskatchewan"},
		{"Id":346, "city":"Unity", "state": "Saskatchewan"},
		{"Id":347, "city":"Creighton", "state": "Saskatchewan"},
		{"Id":348, "city":"Regina", "state": "Saskatchewan"},
		{"Id":349, "city":"Weyburn", "state": "Saskatchewan"},
		{"Id":350, "city":"Eastend", "state": "Saskatchewan"},
		{"Id":351, "city":"Saskatoon", "state": "Saskatchewan"},
		{"Id":352, "city":"Wynyard", "state": "Saskatchewan"},
		{"Id":353, "city":"Esterhazy", "state": "Saskatchewan"},
		{"Id":354, "city":"Shell Lake", "state": "Saskatchewan"},
		{"Id":355, "city":"Yorkton", "state": "Saskatchewan"},
		{"Id":356, "city":"Gravelbourg", "state": "Saskatchewan"},
		{"Id":357, "city":"Levis", "state": "Saskatchewan"},
		{"Id":358, "city":"Levis", "state": "Saskatchewan"},
		{"Id":359, "city":"Carcross", "state": "Yukon Territory"},
		{"Id":360, "city":"White Horse", "state": "Yukon Territory"}
       
    ];

    service.getCountry = function(){
        return countrylist;
    };

    service.getCountryState = function(countryId){
        var states = ($filter('filter')(statelist, {country: countryId}));
        return states;
    };


    service.getStateCity = function(stateId){

        var items = ($filter('filter')(citylist, {state: stateId}));
        return items;
    };
	
	

    return service;


}]);

